# Generated by Django 4.1.6 on 2023-02-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='webapp.ads', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
