# Generated by Django 4.1.6 on 2023-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_comment_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='status',
            field=models.CharField(choices=[('for_moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('for_delete', 'На удаление')], default='for_moderation', max_length=50, verbose_name='Статус'),
        ),
    ]
