# Generated by Django 4.1.6 on 2023-02-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_ads_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'permissions': [('view_not_moderated_ads', 'Просмотр непромодерированных объявлений')]},
        ),
    ]
